### ISSUE TITLE
[bug] will check the not opened profiles after restart

### ISSUE THREAD

**Issue by tjx666** [streetsidesoftware/vscode-spell-checker#3793] opened 2024-11-17 12:48 UTC
like #3400, but happens in [windsurf](https://codeium.com/windsurf) editor

Versions:

```
Windsurf Version: 1.0.2
Codeium Version: 1.26.3
Codeium Commit: 44068b60a7908e67465be714cfee50460790e238
VSCode OSS Version: 1.94.0
Commit: 56025767068f846a4d68adf1914f19f9c34e1375
Date: 2024-11-13T11:02:48.084Z
Electron: 30.5.1
ElectronBuildId: undefined
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.1.0
```

**Comment by Jason3S** [comment] 2024-11-17 15:57
@tjx666,

What version of the Extension are you using?
Can you share a few pictures showing the issue?

**Comment by tjx666** [comment] 2024-11-18 01:30
spell check extension: v3.0.1

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/d2893005-4b74-4ed5-8606-4a859f0f80f3">

reproduce:

1. open `package.json`
2. open `settings.json`
3. close all editors
4. exit windsurf
5. startup windsurf
6. open output panel you will see the spell checker typo suggestion

**Comment by Jason3S** [comment] 2024-11-18 06:26
@tjx666,

The issue should be fixed in v4. Please upgrade if you can.

The issues is caused by a change in behavior from VS Code. They load those files in the background. Previously they used another way of reading them.

**Comment by Jason3S** [comment] 2024-11-18 07:54
@tjx666,

It seems to have been a bug with [https://open-vsx.org](https://open-vsx.org/extension/streetsidesoftware/code-spell-checker), they incorrectly marked the extension as prerelease when it was not. I have changed the manifest to not confuse open-vsx.org's marketplace.

**Comment by Jason3S** [comment] 2024-11-21 06:25
VS Code opens files in the background. When it opens the files, it triggers the spell checker.

There are two work arounds:

1. Use custom decorations: `cSpell.useCustomDecorations`
   <img width="554" alt="image" src="https://github.com/user-attachments/assets/109a0b85-3864-4793-a4d5-1631926c5769">
   The spell checker will handle rendering issues and files opened by VS Code in the background will not show up.
1. The `Spell: Toggle Show Spelling Issues`, `Spell: Show Spelling Issues`, and `Spell: Hide Spelling Issues` commands can be used to show/hide spelling issues. Using these command will clean up and left over issues in the problem pane.
   <img width="380" alt="image" src="https://github.com/user-attachments/assets/a4bbd743-6e39-457b-a41f-304e189856f2">

**Comment by tjx666** [comment] 2024-11-21 18:52
Can't you detect the opened file whether is backgroud files or not?

**Comment by RedCMD** [comment] 2024-11-23 08:32
@tjx666 not easily
`TextEditors` are assigned `TextDocuments`. making easy to go from editor to doc
however `TextDocuments` are **not** assigned `TextEditors`

VSCode has stated they are not going to change that behaviour

**Closed** 2024-12-02 12:22 UTC
Labels: Need Information
