### ISSUE TITLE
Option Allow Compound Words not working

### ISSUE THREAD

**Issue by zeroxia** [streetsidesoftware/vscode-spell-checker#1069] opened 2021-07-20 08:34 UTC
In python, such compound words is very common, e.g., `isclose`, `groupby`.
But although I've enabled this option in both user and workspace settings, those words are still reported as unknown.

Screenshot:

![Screenshot](https://i.imgur.com/W2PTkbv.png)

**Comment by zeroxia** [comment] 2021-07-20 08:36
Interesting: on the screenshot, check line 56, `isinstance` is not reported.

**Comment by cosmolux** [comment] 2021-07-20 19:18
Similarly, in PHP I find DAYOFMONTH and DAYOFWEEK marked as misspellings.  (but not DayOfMonth, etc.)

**Comment by Jason3S** [comment] 2021-07-21 08:59
@zeroxia,

Thank you for the feedback.

`allowCompoundWords` is a mixed bag. Lot's of issues are raised because of missed spelling issues: #802, #560, #345, #324, ...

By design, it only compounds words of at least 3 characters, otherwise many more missed spelled words would be considered correct.

Going forward, the idea is to have a dictionary of common compounded words and to turn off `allowCompoundWords` by default.

**Closed** 2022-11-11 14:19 UTC
