### ISSUE TITLE
Add spell checking to Git commit message input within Source Control section

### ISSUE THREAD

**Issue by ollyrowe** [streetsidesoftware/vscode-spell-checker#625] opened 2020-12-01 11:27 UTC
Would it be possible to add spell checking to the Git commit message text field within the Source Control section of VSCode?

![Capture](https://user-images.githubusercontent.com/46567570/100734421-91a5c200-33c7-11eb-9bd4-4ad20a380ed0.PNG)

**Comment by ollyrowe** [comment] 2020-12-14 12:08
Related issue: https://github.com/Microsoft/vscode/issues/35571

**Comment by Jason3S** [comment] 2020-12-14 16:37
I can add an API endpoint to the extension that will allow to send text to be spell checked. That might work for [Support to use Code Spell Checker for commit messages · Issue #9 · bendera/vscode-commit-message-editor](https://github.com/bendera/vscode-commit-message-editor/issues/9)

**Comment by ollyrowe** [comment] 2020-12-17 08:51
Hi @Jason3S, thanks for the reply. I'm personally not a user of the commit message editor extension. Would there be any way of _this_ extension directly supporting the addition of spell checking within the native VSCode commit message input? If so, I'm more than happy to attempt to implement this feature myself, I'll just need a point in the right direction.

**Comment by Diogo-Rossi** [comment] 2021-07-30 02:03
I would like this feature too.
Maybe dupe of #109

**Comment by bendera** [comment] 2021-09-20 17:02
> I can add an API endpoint to the extension that will allow to send text to be spell checked. That might work for [Support to use Code Spell Checker for commit messages · Issue #9 · bendera/vscode-commit-message-editor](https://github.com/bendera/vscode-commit-message-editor/issues/9)

Hi @Jason3S,

I missed that one of my issues mentioned here, sorry for that. Yes, that endpoint would be great. I would need a function that accepts plain text as a parameter. As I see the exported API only accepts the TextDocument type.

**Comment by Diogo-Rossi** [comment] 2022-08-07 05:07
I think this problem is partially solved with [this update of VS Code](https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor)

**Comment by Jason3S** [comment] 2022-08-07 18:04
@Diogo-Rossi,

Yes, the new changes have helped.

I'm going to close this for now since it seems to be mostly working.

There are some issues on the VS Code side, but I suspect that they will get resolved.

**Closed by Jason3S** 2022-08-07 18:04 UTC
Labels: enhancement

**Comment by Diogo-Rossi** [comment] 2022-08-09 19:25
I thought it was a workaround to get the message spell checked, to use a editor ...

But you actually did it in source control commit input box.

Thankyou

**Comment by Diogo-Rossi** [comment] 2022-08-09 19:26
I thought it was a workaround to get the message spell checked, using a editor ...

But you actually did it in source control commit input box.

Thank you

**Comment by Jason3S** [comment] 2022-08-09 21:27
@Diogo-Rossi,

Actually, @lszomoru, updated VS Code to make this possible.
