### ISSUE TITLE
Quick fix not work with mouse

### ISSUE THREAD

**Issue by machsix** [streetsidesoftware/vscode-spell-checker#366] opened 2019-07-23 02:30 UTC
"Quick fix" works with if the hovered window is open with "Ctrl+." but doesn't work with mouse clicking. There is nothing happened after I click the correct word or use `tab` and `enter` to select the word. But "Add to dictionary" works.  Is this a bug or I miss something?

I tried to set `"cSpell.logLevel": "Debug"` but nothing shows at the moment of clicking.

**Comment by Jason3S** [comment] 2019-07-26 13:17
Duplicate of #362

**Comment by Jason3S** [comment] 2019-07-26 13:17
Thank you.

**Closed** 2019-07-28 13:59 UTC
Labels: duplicate
