### ISSUE TITLE
with Italian mistyped words underlined but no hint for fixing

### ISSUE THREAD

**Issue by rcorsari** [streetsidesoftware/vscode-spell-checker#1584] opened 2021-12-07 09:35 UTC
Hello
I have the latest Visual Studio Code (currently 1.62.3)

PREMISE: I have ALL the extensions disabled

I have installed vscode-spell-checker and the Italian add-on

I have enabled it 

It works partially

Mistyped words are underlined but when I hover the mouse on the mistyped word I get this popover "Unknown word", then I fix the word and the underlying disappears.

I think this is not the expected behavior ... the word is recognized as wrong while mistyped and it is recognized correct when correctly typed ... so what's wrong with the extension?

Thank you

**Comment by Jason3S** [comment] 2021-12-07 09:55
@rcorsari,

Thank you for the feedback.
The issue is not clear to me. Would you please provide a couple of screen shots demonstrating the issue?

Kind regards,
Jason

**Comment by Jason3S** [comment] 2021-12-07 09:58
Are you seeing something like this:
![image](https://user-images.githubusercontent.com/3740137/145007615-0cc7463b-4f63-4a21-b9e6-f34a8d1229c4.png)

If that is the case, `Quick Fix` should give you a list of suggestions.

**Comment by rcorsari** [comment] 2021-12-07 10:39
OUCH!!!! Sorry 
yes, that was the point ... unfortunately we are all succubus of spell checking extensions from browsers

when you right click the underlined word, it pops a contextual menu with the list of words, much more intuitive 

Thank you for the hint, it works , so no issue .

Though for a spell checker I would suggest the approach of common spell checkers, that list to pop is really useful I mean, without pressing keyboard combinations or clicking on quick fix .. we know we want a quick fix, if we don't want it, we won't click nothing on the list

do you agree?

Thank you for your prompt support

**Comment by Jason3S** [comment] 2021-12-07 10:47
That part of the behavior is controlled by VS Code. An extension does not have much control over what is displayed.

**Comment by Jason3S** [comment] 2021-12-07 10:48
I'm going to close this for now.

**Closed by Jason3S** 2021-12-07 10:48 UTC
