### ISSUE TITLE
 No spellchecking for files in virtual workspaces? 

### ISSUE THREAD

**Issue by devgid** [streetsidesoftware/vscode-spell-checker#2034] opened 2022-06-20 17:18 UTC
Spell checking doesn't work in virtual workspaces.

Can test this using the extension Github Repositories.

https://code.visualstudio.com/api/extension-guides/virtual-workspaces

**Comment by devgid** [comment] 2022-06-20 17:21
Was previously logged but auto closed. #846

**Comment by Jason3S** [comment] 2022-06-21 17:11
@devgid,

Thank you for the request. This is a duplicate of #1554. Significant funding is necessary to enable the development of Web based spell checking. At the moment we do not have the funds to do it. If it is important to you and your organization, please consider sponsoring us: [Spell Checker for Visual Studio Code - Open Collective](https://opencollective.com/code-spell-checker).

#846 is about setting the correct manifest values to let VS Code know if we support virtual-workspaces. The spell checker does not currently support them.

**Closed** 2022-06-27 07:18 UTC
