### ISSUE TITLE
Web support.

### ISSUE THREAD

**Issue by proJM1** [streetsidesoftware/vscode-spell-checker#1986] opened 2022-06-03 03:07 UTC
Can we please add web support so that we can use the extension on the vscode for the web?
vscode for the web: https://vscode.dev

**Comment by Jason3S** [comment] 2022-06-03 05:45
@proJM1,

Thank you for the feedback. This a duplicate of #1554.

This extension does work on [GitHub Codespaces](https://docs.github.com/en/codespaces/overview) and [Gitpod](https://www.gitpod.io/).

**Closed by Jason3S** 2022-06-03 05:45 UTC
