### ISSUE TITLE
ESLint + Prettier stops formatting code when spell checker is enabled 

### ISSUE THREAD

**Issue by ahmadawais** [streetsidesoftware/vscode-spell-checker#235] opened 2018-06-28 17:43 UTC
I really liked it. Ext worked pretty great. 

ONLY AND BIG PROBLEM — it didn't let ESLint + Prettier format my code and I've been pulling my hair to trying to fix things and after one by one enabling disabling every extension did I end up here — cSpell has issues. Big ones.

**Comment by Jason3S** [comment] 2018-06-29 07:12
Thank you.

I would be happy to help, but I need some more information.

Which extensions are you using for ESLint + Prettier? The more information you give, the easier it is for me to reproduce.

What do you mean by "it didn't let ESLint + Prettier format my code"? The spell checker doesn't change your code, it just reports spelling issues to VS Code.

**Comment by ahmadawais** [comment] 2018-06-29 09:06
@Jason3S 

- [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

Settings 

```json
"editor.formatOnSave": true,
"editor.formatOnPaste": true,
// ESLint.
"eslint.enable": true,
"eslint.autoFixOnSave": true,
"eslint.alwaysShowStatus": true,
"eslint.nodePath": "./node_modules/.bin/eslint",
// Prettier.
"prettier.eslintIntegration": true,
"prettier.printWidth": 120,
"prettier.singleQuote": true,
"prettier.tabWidth": 4,
"prettier.useTabs": true,

```

With the above two extensions, which are used by millions of developers to auto format their code, if cSpell is active, the auto-formatting doesn't work. cSpell somehow disturbs this auto-formatting which makes for a poor and unpredictable code formatting experience.

Let me know if you need more info.

**Comment by Jason3S** [comment] 2018-07-05 07:50
Thank you. I'll try it out.

**Comment by Jason3S** [comment] 2018-07-05 08:46
Would you try setting:

```
"eslint.alwaysShowStatus": false,
```

**Comment by Jason3S** [comment] 2018-07-08 09:57
I am still not able to reproduce the behavior you are describing.

For me it reformats on save and on paste just fine.

Maybe make a `.gif` of the behavior you are seeing and describe how you expect it to work.

**Comment by BorntraegerMarc** [comment] 2019-03-17 15:34
@Jason3S for me it looks like this:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7549295/54493628-71239480-48d2-11e9-9235-2fd3d2d86046.gif)


I think there's somehow an incompatibility between this plugin and prettier (https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

**Comment by BorntraegerMarc** [comment] 2019-03-17 15:51
I think the issue only happens if a file has a lot of spelling errors

**Comment by Jason3S** [comment] 2019-06-12 16:28
This should be fixed with the latest release. See: #349

**Closed by Jason3S** 2019-06-12 16:28 UTC
Labels: Done / Fixed
