### ISSUE TITLE
Don't mark possessives with apostrophes as incorrect

### ISSUE THREAD

**Issue by nicchristeller** [streetsidesoftware/vscode-spell-checker#397] opened 2019-10-31 23:06 UTC
Using possessive apostrophes (e.g. ` the level's code`) in comments leads to the word to be highlighted as misspelled.

Words with apostrophes like this should have the root word checked (i.e. "level" in this case) so that every noun that may be used with a possessive doesn't need to exist in the dictionaries twice.

**Comment by Jason3S** [comment] 2019-11-02 08:02
`level's` is in the US English dictionary, but not in the GB dictionary.

**Comment by ankostis** [comment] 2020-04-05 15:34
@Jason3S: it shouldn't matter whether `level's` is in a dictionary - just `level`.
Practically, the `'s` must be clipped before checking word.

**Comment by ankostis** [comment] 2020-04-05 15:37
Dupe of #164, 232, and  related to #268.

**Closed** 2021-09-29 15:01 UTC
Labels: Done / Fixed
