### ISSUE TITLE
Spell check for Jupyter Notebooks

### ISSUE THREAD

**Issue by apptimise** [streetsidesoftware/vscode-spell-checker#420] opened 2020-01-31 18:00 UTC
I use Jupyter Notebook inside VSCode heavily. Wondering if there is a way to enable the spell checker for the .ipynb files?

**Comment by Jason3S** [comment] 2020-02-03 23:16
There are a couple of way to do this:

`F1 Enable Spell Checking Document Language`

![image](https://user-images.githubusercontent.com/3740137/73699054-127e2980-46e3-11ea-927d-66739f19c999.png)

Due to a recent bug in VS Code, you might need to restart VS Code.

If you go to VS Code settings, and search for `cspell.enabledLanguageIds`, you can add the language ID. 

![image](https://user-images.githubusercontent.com/3740137/73698879-a1d70d00-46e2-11ea-9f17-48e6830f40c4.png)

**Comment by apptimise** [comment] 2020-02-04 19:10
thanks, but what language should I add? It works with Python (i.e. the .py files), but not with the Jupyter Notebooks. Tried the first approach as well, got an error "_Reduce of empty array with no initial value_", and restarting the VSCode didn't help.

**Comment by Jason3S** [comment] 2020-02-04 21:31
![image](https://user-images.githubusercontent.com/3740137/73788874-191da700-479e-11ea-89ad-a44c363fcaa2.png)

`jupyter` - all lowercase.

**Comment by Jason3S** [comment] 2020-02-04 21:42
Do you have some good examples I can try? The ones I found do not seem to load.
Plus, what plug-in are you using to edit / display them?

**Comment by christian96l** [comment] 2020-04-28 07:31
I use the [Microsoft Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) on Remote-WSL and the spell checker also seems not to work (even after restart of VSCode).

![SharedScreenshot](https://user-images.githubusercontent.com/38144453/80459624-eca7a000-8932-11ea-9136-e6618e81287c.jpg)
![SharedScreenshot](https://user-images.githubusercontent.com/38144453/80459512-c1bd4c00-8932-11ea-8ada-5ed8538b1a73.jpg)

I think the spell checker only works with the raw text data and not in the extension view.

**Comment by raghavendra-musubi** [comment] 2020-07-24 15:22
We need a spell checker for Jupyter Notebooks in VSCode.

**Comment by mikessut** [comment] 2021-01-22 22:27
I've tried this solution, but still can't get spell check in ipynb.

**Comment by YiquanGu** [comment] 2021-05-03 04:27
Just wondering whether there's been workable solution within vscode-spell-checker or a different extension emerged since then?

**Comment by Jason3S** [comment] 2021-09-01 12:14
Update

I took a look at this a while ago. The issue is that the Jupyter Notebooks extension controls what is displayed. The last time I checked, it was not possible to interact with the Notebook from another extension. That might have changed. When I get the chance, I'll take another look.

**Comment by Jason3S** [comment] 2021-09-02 13:17
Good news!!!

With the new Notebook UI in VS Code ([The Coming of Age of Notebooks](https://code.visualstudio.com/blogs/2021/08/05/notebooks)), it is now possible to run spell checking!. 

![image](https://user-images.githubusercontent.com/3740137/131843583-8ea6f7b4-7b94-4a8d-84c3-9ecaf524b69a.png)

Note: It must be in the New UI! See [VS Code Issue #7021](https://github.com/microsoft/vscode-jupyter/issues/7021#issuecomment-899413080) on how to open a Notebook with the new UI.

Old UI:
![image](https://user-images.githubusercontent.com/3740137/131844428-4a36f775-ad97-4b60-8302-af621bcc21f2.png)

**Comment by Jason3S** [comment] 2022-02-04 12:45
@VeronicaCodes,

It should be working.
Do you see this at the bottom: 
![image](https://user-images.githubusercontent.com/3740137/152531254-bd7c8b5a-838b-4071-8965-38f017b5b09f.png)

The `spell` part is important.

**Comment by Jason3S** [comment] 2022-02-04 12:58
This is what I have:
![image](https://user-images.githubusercontent.com/3740137/152532846-2ab3cacc-37c6-4b10-aeaa-b29c81e47bf5.png)

@VeronicaCodes,
I'm going to close this issue. It looks like it was left open by accident. Please open a new issue with some more details on what your are seeing.

**Closed by Jason3S** 2022-02-04 12:58 UTC
Labels: enhancement
